# config/packages/fos_user.yaml

fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     App\Application\Sonata\UserBundle\Entity\User
   
    group:
        group_class:   App\Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

    service:
        user_manager: sonata.user.orm.user_manager
        mailer: fos_user.mailer.twig_swift   
        
    from_email:
        address: vigilavi #"%mailer_user%"
        sender_name: admin #"%mailer_user%"

    registration:
        form:
            type: App\Form\RegistrationFormType
    use_authentication_listener: false
