sonata_admin:
    title: 'Vigilavi'
    show_mosaic_button: false
    search: false
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
