sonata_admin:
    title: 'Vigilavi'
    show_mosaic_button: false
    search: false
    dashboard:
        groups:
          app.admin.group.dashboard:
                on_top:       true
                label: ~
                label_catalogue: App
                icon: '<i class="fa fa-home"></i>'
                items:
                    - route: sonata_admin_dashboard
                      label: app.admin.group.dashboard


          app.admin.group.users:
                on_top:          true
                label:           app.admin.group.users
                label_catalogue: App
                icon:            '<i class="fa fa-user"></i>'
                items:
                    - app.admin.user

          app.admin.group.origins:
                on_top:       true
                label: app.admin.group.origins
                label_catalogue: App
                icon: '<i class="fa fa-map-marker"></i>'
                items:
                    - app.admin.origin

          app.admin.group.words:
                on_top:       true
                label: app.admin.group.words
                label_catalogue: App
                icon: '<i class="fa fa-tags"></i>'
                items:
                    - app.admin.wordset
                    
          app.admin.group.reports:
                on_top:       true
                label: app.admin.group.reports
                label_catalogue: App
                icon: '<i class="fa fa-folder-open"></i>'
                items:
                    - app.admin.report

          app.admin.group.logs:
                on_top:          true
                label: app.admin.group.logs
                label_catalogue: App
                icon: '<i class="fa fa-database"></i>'
                items:
                    - app.admin.log_entry
        blocks:
            -
                class:    col-lg-12 col-xs-12          # twitter bootstrap responsive code
                position: top                        # zone in the dashboard
                type:     sonata.block.service.empty  # block id # block i
            -
                class:    col-lg-2 col-xs-3          # twitter bootstrap responsive code
                position: bottom                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id # block id
                roles: ['ROLE_ADMIN']
                settings:
                    code:  app.admin.user    # admin code - service id
                    icon:  fa-user                  # font awesome icon
                    text:  app.user.stats.inactive  
                    color: bg-red
                    filters:                         # filter values
                        enabled: { value: 2 }
            -
                class:    col-lg-4 col-xs-6          # twitter bootstrap responsive code
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                roles: ['ROLE_ADMIN']
                settings:
                    code:  app.admin.user    # admin code - service id
                    icon:  fa-user                  # font awesome icon
                    text:  app.user.stats.total            # static text or translation message
                    color: bg-blue                 # colors: bg-green, bg-red and bg-aqua

            -
                class:    col-lg-2 col-xs-3          # twitter bootstrap responsive code
                position: bottom                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id # block id
                roles: ['ROLE_ADMIN']
                settings:
                    code:  app.admin.user    # admin code - service id
                    icon:  fa-user                  # font awesome icon
                    text:  app.user.stats.active  
                    color: bg-green
                    filters:                         # filter values
                        enabled: { value: 1 }

    security:
        handler: sonata.admin.security.handler.role
        role_admin: ROLE_SONATA_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
    assets:
        extra_stylesheets:
            - bundles/sonatatranslation/css/sonata-translation.css

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
