# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Util\SyslogDBCollector:
        $sophosDNS: '%env(SOPHOS_DNS)%'
        $sophosUser: '%env(SOPHOS_USER)%'
        $sophosPass: '%env(SOPHOS_PASS)%'
        
    app.admin.emailsubscription:
        class: App\Admin\EmailSubscriptionAdmin
        arguments: [~, App\Entity\EmailSubscription, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: EmailSubscription}
        calls:
            - [ setTranslationDomain, [messages]]
            
    app.admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Application\Sonata\UserBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }
        calls:
            - [ setTranslationDomain, [messages]]

    app.admin.headquarter:
        class: App\Admin\HeadquarterAdmin
        arguments: [~, App\Entity\Headquarter, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Headquarter }

    app.admin.log_entry:
        class: App\Admin\LogEntryAdmin
        arguments: [~, App\Entity\LogEntry, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: LogEntry }
        calls:
            - [ setTranslationDomain, [messages]]

    app.admin.origin:
        class: App\Admin\OriginAdmin
        arguments: [~, App\Entity\Origin, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Origin}
        calls:
            - [ setTranslationDomain, [messages]]
            
    app.admin.outcome:
        class: App\Admin\OutcomeAdmin
        arguments: [~, App\Entity\Outcome, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Outcome }
        calls:
            - [ setTranslationDomain, [messages]]
            
    app.admin.report:
        class: App\Admin\ReportAdmin
        arguments: [~, App\Entity\Report, App\Controller\ReportCRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Report }
        calls:
            - [ setTranslationDomain, [messages]]
            - [addChild, ['@app.admin.outcome', 'report']]
            - [setTemplate, ['show', 'report_admin/show.html.twig']]

    app.admin.word_set:
        class: App\Admin\WordSetAdmin
        arguments: [~, App\Entity\WordSet, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: WordSet }
        calls:
            - [ setTranslationDomain, [messages]]
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
